name = "PaperPlots"
uuid = "a3f1b214-3a5a-4a90-8a87-66f1e8e10212"
authors = ["Zenna Tavares"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
